# Generated by Django 5.1 on 2024-08-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0002_galery_name_galery_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
