# Generated by Django 5.1 on 2024-08-19 15:47

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_rename_section_topic_lesson_remove_lesson_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='lesson',
            new_name='section',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='section',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='image',
        ),
        migrations.AddField(
            model_name='lesson',
            name='image',
            field=models.ImageField(default=2, upload_to='lesson/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='lesson.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(upload_to='section/'),
        ),
    ]
