# Generated by Django 5.1 on 2024-08-19 15:48

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_rename_lesson_topic_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='image',
        ),
        migrations.RemoveField(
            model_name='section',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='section',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='video_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lesson.topic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(default=1, upload_to='section/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='topicss', to='lesson.section'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='image',
            field=models.ImageField(upload_to='lesson/'),
        ),
    ]
