# Generated by Django 5.1 on 2024-08-19 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0004_remove_lesson_image_remove_section_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='lesson.section'),
        ),
    ]
