# Generated by Django 5.1 on 2024-08-19 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_alter_topic_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='section',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='lesson',
            new_name='section',
        ),
    ]
